### ISSUE TITLE
How to disable notification shown in dialog

### ISSUE THREAD

**Issue by kavathiyamahesh** [infobip/mobile-messaging-sdk-android#6] opened 2019-02-14 10:05 UTC
Hello Team

SDK: Version 2.0.6@aar

I am sending push notification from infobip portal when my application is available on the foreground.
So I am receiving notification on notification panel along with dialog with title and body with OPEN and CANCEL button.

So how to remove/disable this dialog when notification receive when the application is on foreground mode?

Thanks

**Comment by tjuric** [comment] 2019-02-14 10:15
Hi @kavathiyamahesh,

This foreground dialog is shown only if you use an option to show in-app notification - this triggers the dialog inside the app. 

This option is set to false by default. Please, check on our portal that when you send notification `Show in-app notification` is unchecked like shown below.

<img width="425" alt="screenshot 2019-02-14 at 11 09 59" src="https://user-images.githubusercontent.com/2648565/52780075-bb062a00-3049-11e9-9663-76a5e0802c2c.png">

**Comment by kavathiyamahesh** [comment] 2019-02-14 10:40
Hello @tjuric 

I have checked this and it's always unchecked while we are sending a notification from infobip, still, I am able to see dialog inside the app with the latest SDK: Version 2.0.6@aar

Thanks

**Comment by tjuric** [comment] 2019-02-14 11:06
Can you send one more message from portal and provide us app logs?

**Comment by kavathiyamahesh** [comment] 2019-02-14 11:26
Hello @tjuric 

Please find logs


V/MobileMessaging: RECEIVED MESSAGE FROM GCM
    {
      "body": "login",
      "customPayload": {
        "nameValuePairs": {
          "nativePageName": "login"
        }
      },
      "from": "1017066197845",
      "inAppStyle": "MODAL",
      "internalData": "{\"sendDateTime\":1550142752718,\"inApp\":false}",
      "messageId": "yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA\u003d\u003d",
      "receivedTimestamp": 0,
      "seenTimestamp": 0,
      "sentTimestamp": 1550142752718,
      "silent": false,
      "sound": "default",
      "status": "UNKNOWN",
      "title": "Login ",
      "vibrate": true
    }
2019-02-14 16:42:34.000 3794-5269/? D/SamsungAlarmManager: Cancel Alarm calling from uid:10023 pid :19111 / op:PendingIntent{22689ff: PendingIntentRecord{defba0c com.google.android.gms broadcastIntent}}
2019-02-14 16:42:34.037 12616-20104/ D/MobileMessaging: Sending DR: yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA==
2019-02-14 16:42:34.037 3794-5269/? D/StorageManagerService: getExternalStorageMountMode : 3
2019-02-14 16:42:34.038 3794-5269/? D/StorageManagerService: getExternalStorageMountMode : final mountMode=1, uid : 10296, packageName : com.google.android.apps.searchlite
2019-02-14 16:42:34.039 3794-5269/? I/ApplicationPolicy: isApplicationExternalStorageWhitelisted:com.google.android.apps.searchlite user:0
2019-02-14 16:42:34.039 3794-5269/? D/ApplicationPolicy: isApplicationExternalStorageWhitelisted: DO is not enabled on user 0. Allowed.
2019-02-14 16:42:34.039 3794-5269/? D/ActivityManager: package  com.google.android.apps.searchlite, user - 0 is SDcard whitelisted
2019-02-14 16:42:34.039 3794-5269/? I/ApplicationPolicy: isApplicationExternalStorageBlacklisted:com.google.android.apps.searchlite user:0
2019-02-14 16:42:34.039 3794-5269/? D/ApplicationPolicy: isApplicationExternalStorageBlacklisted: DO is not enabled on user 0. Allowed.
2019-02-14 16:42:34.047 3794-5416/? D/ConnectivityService: filterNetworkStateForUid() uid: 10775 networkInfo: [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "Mobiquity_CORP", failover: false, available: true, roaming: false, metered: false]
2019-02-14 16:42:34.061 3794-5269/? I/ActivityManager: Start proc 20105:com.google.android.apps.searchlite/u0a296 for service com.google.android.apps.searchlite/com.firebase.jobdispatcher.GooglePlayReceiver
2019-02-14 16:42:34.064 3794-5268/? D/SamsungAlarmManager: setInexact Intent (T:2/F:0/AC:false) 20190214T170626 - CU:10023/CP:19111
2019-02-14 16:42:34.068 20105-20105/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-02-14 16:42:34.070 20105-20105/? E/libpersona: scanKnoxPersonas
2019-02-14 16:42:34.071 20105-20105/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
2019-02-14 16:42:34.077 20105-20105/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SM-G950F_8.0.0_0016, [-1 -1 -1 -1 0 1]
2019-02-14 16:42:34.080 20105-20105/? I/SELinux: SELinux: seapp_context_lookup: seinfo=apm, level=s0:c512,c768, pkgname=com.google.android.apps.searchlite 
2019-02-14 16:42:34.108 12616-20104/ D/MobileMessaging: Dispatching message to org.infobip.mobile.messaging.interactive.MobileInteractiveImpl
2019-02-14 16:42:34.116 12616-12722/ V/MobileMessaging: SYNC MESSAGES >>>
    {
      "drIDs": [
        "yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA\u003d\u003d"
      ],
      "mIDs": [
        "h4YvtIJJKB99r2N+BeGvSh6sV4FBaoYR+YimirecT881Q/V9B6ai0tBBwL8IVaGG90hlwaDzSugKaqjQl8jCmw\u003d\u003d",
        "CkyI0OsVvul/MFK6G9RBa3fqlsStYdff1FjtyUxyQAkzlROyH6jPxYFF+xP3haIY0OmBMj0WXarNh5BGgwj2rg\u003d\u003d",
        "DepXBU1uljt31Dlfp6hZCIUwEvu7URyX9D3FZiIJ07w1Q/V9B6ai0hr9tIRDVVrlO5PSoKBf1IK94TgN0meMsg\u003d\u003d",
        "bRg6mskpIHHbLSjBDqpGMZgdaImO94QQN0oieIshjQo1Q/V9B6ai0toPDQAe3UDXrmUltnMHngoxbWLilxfymg\u003d\u003d",
        "7VWy0AmJXb/YI1C4oPbL1Ax+LyBx0KAZxvkY1MDvPagzlROyH6jPxRmfoPlchEqM8T/pDApcUI/Nh5BGgwj2rg\u003d\u003d",
        "qAQEr/CER3XXZsAPiN0EjcJh4qHoP4+jO07q4LlC03g1Q/V9B6ai0tBBwL8IVaGGwOXdXbhZhuslED747s8ZuQ\u003d\u003d",
        "Anz64d2SzqwkUsLsOX78SOr/8nUcWpx57yOBo5kCJNY1Q/V9B6ai0m8hXE0fSdZYTGCelxaqcEL+BOLmRGP8dA\u003d\u003d",
        "yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA\u003d\u003d",
        "HJ01V6N5X4ivO9A31fSKaZz2sGJ9PtYERTIr6b4QEmg1Q/V9B6ai0hr9tIRDVVrlNxsiiaymlKZpPdFZZNRrug\u003d\u003d",
        "iNjPh3403mgm6dX+IFrGpyiLSw0632lmCzdjOmEPZgs1Q/V9B6ai0m8hXE0fSdZYS0w0DplZuMmU7+gBk74HAw\u003d\u003d",
        "qEwqKEcJKgWqXZpOEd5EY1zwlqLmx+J1iA91Pt9oTU81Q/V9B6ai0m8hXE0fSdZY2Mv1e7tMBjch6BLH3OgGsA\u003d\u003d",
        "OVfhLxiShrBUEOUZwrGwfc8yOQhlS2ULnS0a2nmk7RQ1Q/V9B6ai0tBBwL8IVaGGtUgxlljB6yggsSt0nv8ttQ\u003d\u003d",
        "NUxRmeZY9U/mY3ztFh/IzMjFBwPV0A+1wAysmycpWOY1Q/V9B6ai0uaJC2rze8gW7G4bUWxWxZj6RYJzo+6vSg\u003d\u003d",
        "Z6RB76K/KCXmAZp1Oh/RE2/XM4zOgU9rlJ1GHHv9mto1Q/V9B6ai0tBBwL8IVaGG9diofr15uxlqNJAiTgFS8w\u003d\u003d"
      ]
    }
2019-02-14 16:42:34.123 12616-20104/ D/MobileMessaging: Saving message: yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA==
2019-02-14 16:42:34.124 12616-20104/ D/MobileMessaging: Skipping save message: yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA==
2019-02-14 16:42:34.126 20105-20105/? D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
2019-02-14 16:42:34.127 20105-20105/? D/ActivityThread: Added TimaKeyStore provider
2019-02-14 16:42:34.128 12616-20104/ D/MobileMessaging: Message is silent: false
2019-02-14 16:42:34.129 12616-12722/ D/MMHTTP: REQUEST: Request(httpMethod=POST, uri=https://mobile.infobip.com/mobile/5/messages, apiKey=882e47c351e9689152fe5787f8f16c1e-b80ecc28-aa1e-411c-83b2-f8a0e66b26e6, credentials=null, headers={applicationcode=[8334909acc], pushregistrationid=[b4198495-a12e-46bd-83ca-cd9a5570c016], foreground=[true]}, queryParams={platformType=[GCM]}, body=SyncMessagesBody(mIDs=[h4YvtIJJKB99r2N+BeGvSh6sV4FBaoYR+YimirecT881Q/V9B6ai0tBBwL8IVaGG90hlwaDzSugKaqjQl8jCmw==, CkyI0OsVvul/MFK6G9RBa3fqlsStYdff1FjtyUxyQAkzlROyH6jPxYFF+xP3haIY0OmBMj0WXarNh5BGgwj2rg==, DepXBU1uljt31Dlfp6hZCIUwEvu7URyX9D3FZiIJ07w1Q/V9B6ai0hr9tIRDVVrlO5PSoKBf1IK94TgN0meMsg==, bRg6mskpIHHbLSjBDqpGMZgdaImO94QQN0oieIshjQo1Q/V9B6ai0toPDQAe3UDXrmUltnMHngoxbWLilxfymg==, 7VWy0AmJXb/YI1C4oPbL1Ax+LyBx0KAZxvkY1MDvPagzlROyH6jPxRmfoPlchEqM8T/pDApcUI/Nh5BGgwj2rg==, qAQEr/CER3XXZsAPiN0EjcJh4qHoP4+jO07q4LlC03g1Q/V9B6ai0tBBwL8IVaGGwOXdXbhZhuslED747s8ZuQ==, Anz64d2SzqwkUsLsOX78SOr/8nUcWpx57yOBo5kCJNY1Q/V9B6ai0m8hXE0fSdZYTGCelxaqcEL+BOLmRGP8dA==, yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA==, HJ01V6N5X4ivO9A31fSKaZz2sGJ9PtYERTIr6b4QEmg1Q/V9B6ai0hr9tIRDVVrlNxsiiaymlKZpPdFZZNRrug==, iNjPh3403mgm6dX+IFrGpyiLSw0632lmCzdjOmEPZgs1Q/V9B6ai0m8hXE0fSdZYS0w0DplZuMmU7+gBk74HAw==, qEwqKEcJKgWqXZpOEd5EY1zwlqLmx+J1iA91Pt9oTU81Q/V9B6ai0m8hXE0fSdZY2Mv1e7tMBjch6BLH3OgGsA==, OVfhLxiShrBUEOUZwrGwfc8yOQhlS2ULnS0a2nmk7RQ1Q/V9B6ai0tBBwL8IVaGGtUgxlljB6yggsSt0nv8ttQ==, NUxRmeZY9U/mY3ztFh/IzMjFBwPV0A+1wAysmycpWOY1Q/V9B6ai0uaJC2rze8gW7G4bUWxWxZj6RYJzo+6vSg==, Z6RB76K/KCXmAZp1Oh/RE2/XM4zOgU9rlJ1GHHv9mto1Q/V9B6ai0tBBwL8IVaGG9diofr15uxlqNJAiTgFS8w==], drIDs=[yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA==]))
2019-02-14 16:42:34.132 3794-5268/? I/ActivityManager: DSS on for com.google.android.apps.searchlite and scale is 1.0
2019-02-14 16:42:34.142 12616-12722/ I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-02-14 16:42:34.143 12616-12722/ I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-02-14 16:42:34.150 12616-12722/ V/NativeCrypto: SSL shutdown failed: ssl=0x78b87b33c8: I/O error during system call, Broken pipe
2019-02-14 16:42:34.164 12616-20104/ V/MobileMessaging: NOTIFY FOR MESSAGE
    {
      "body": "login",
      "customPayload": {
        "nameValuePairs": {
          "nativePageName": "login"
        }
      },
      "from": "1017066197845",
      "inAppStyle": "MODAL",
      "internalData": "{\"sendDateTime\":1550142752718,\"inApp\":false}",
      "messageId": "yFebMIOv866jDzllZ5NdILQ/IBk7JktTZQRMbglfRLw1Q/V9B6ai0oE6wM6ZP0n1mpBfXd/czR+/ZfsrxscwtA\u003d\u003d",
      "receivedTimestamp": 1550142754036,
      "seenTimestamp": 0,
      "sentTimestamp": 1550142752718,
      "silent": false,
      "sound": "default",
      "status": "UNKNOWN",
      "title": "Login ",
      "vibrate": true
    }
2019-02-14 16:42:35.022 12616-12722/ V/MobileMessaging: SYNC MESSAGES <<<
    {
      "payloads": []
    }
2019-02-14 16:42:35.024 12616-12616/ V/MobileMessaging: Result wrapper: 
    {
      "cancelled": false,
      "result": []
    }

**Comment by kavathiyamahesh** [comment] 2019-02-14 11:39
@tjuric I see that my logs are deleted but I hope you have seen and then removed due to some security reason

**Comment by tjuric** [comment] 2019-02-14 11:43
Yes, I've deleted your logs for security reasons. 
We're checking your logs and trying to reproduce your issue. I'll update you on the state.

**Comment by tjuric** [comment] 2019-02-14 14:23
@kavathiyamahesh we've found a bug in our SDK. New version is released with bug-fix for the issue that you reported. Issue appeared when GCM is used in the application, but isn't present for Firebase. 

Please, update to the latest version [2.0.7](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/2.0.7).

Also, I'd advise you not to use GCM but migrate your app to Firebase since GCM is deprecated and most of GCM services will be turned off on April this year. You might read about it [here](https://developers.google.com/cloud-messaging/faq).

If you used older version of our SDK 1.x, read migration docs to Firebase here https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/1.16.0.

**Comment by tjuric** [comment] 2019-02-14 16:07
Closing this issue since we've received confirmation from our support that it's resolved.

**Closed as completed by tjuric** 2019-02-14 16:07 UTC

**Comment by kavathiyamahesh** [comment] 2019-02-15 08:24
Hello @tjuric 

Thanks for the quick update.

I have added only our SDK **org.infobip.mobile.messaging.api:infobip-mobile-messaging-android-sdk:2.0.6@aar**  

After I have added **google_app_id** and **infobip_application_code** and I have created a project in Firebase consol so how it's considered as GCM?

Thanks

**Comment by tjuric** [comment] 2019-02-15 12:44
Can you please check if you reference `play-services-gcm` explicitly in your `build.gradle`? If that's the case, then you can safely remove it and SDK will pick up Firebase automatically. 

Otherwise we treat it as if you want to use GCM. From the Infobip side we automatically use GCM if it is included in the app or include Firebase ourselves if GCM is not there. It is done for backwards compatibility.

**Comment by kavathiyamahesh** [comment] 2019-02-15 13:14
Hello @tjuric 

Got it, Thanks
Yeah, we are using **play-services-gcm** for some other reason and we already planned for removing it before April.

Thanks for your quick support, appreciate it.!!!

**Comment by tjuric** [comment] 2019-02-15 13:33
You're welcome @kavathiyamahesh!
