### ISSUE TITLE
Randomly app crash due to Infobip sdk

### ISSUE THREAD

**Issue by jkhasatiya** [infobip/mobile-messaging-sdk-android#14] opened 2019-09-10 06:37 UTC
Hello,

We found random crash in our app due to Infobip sdk. As Issue reproduced randomly no particular steps available.

- Infobip sdk [2.1.1@aar].
- Android OS : Any

Please provide your feedback asap.

Thanks

Crash logs: 
`java.lang.RuntimeException: java.lang.NullPointerExceptionat android.app.job.JobService$JobHandler.handleMessage(JobService.java:147)at android.os.Handler.dispatchMessage(Handler.java:110)at android.os.Looper.loop(Looper.java:203)at android.app.ActivityThread.main(ActivityThread.java:6414)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)Caused by: java.lang.NullPointerExceptionat java.util.Hashtable.put(Hashtable.java:442)at org.infobip.mobile.messaging.mobile.MobileApiResourceProvider.getGenerator(MobileApiResourceProvider.java:165)at org.infobip.mobile.messaging.mobile.MobileApiResourceProvider.getMobileApiAppInstance(MobileApiResourceProvider.java:120)at org.infobip.mobile.messaging.MobileMessagingCore.installationSynchronizer(MobileMessagingCore.java:1614)at org.infobip.mobile.messaging.MobileMessagingCore.syncInstallation(MobileMessagingCore.java:341)at org.infobip.mobile.messaging.MobileMessagingCore.performSyncActions(MobileMessagingCore.java:324)at org.infobip.mobile.messaging.MobileMessagingCore.retrySyncOnNetworkAvailable(MobileMessagingCore.java:319)at org.infobip.mobile.messaging.platform.MobileMessagingJobService.onStartJob(MobileMessagingJobService.java:48)`

**Comment by jkhasatiya** [comment] 2019-09-17 11:10
Hello, Is there any update on it?

**Comment by tjuric** [comment] 2019-09-17 11:28
HI @jkhasatiya we'll release bugfix version this week. I'll notify you here once it will be released.

**Comment by jkhasatiya** [comment] 2019-09-17 12:02
@tjuric Thanks for the update.

**Comment by tjuric** [comment] 2019-09-20 08:15
New version [2.2.0](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/2.2.0) was released yesterday. Please try it out and provide us your feedback.

**Comment by jkhasatiya** [comment] 2019-09-20 08:16
@tjuric Sure. Thanks.

**Comment by jkhasatiya** [comment] 2019-10-10 09:52
@tjuric Hi,
We can still reproduce this issue with latest Infobip sdk[2.2.0@aar]. Can you please check this on priority. For reference please refer crash log mentioned above.

**Comment by tjuric** [comment] 2019-10-16 08:58
Hi @jkhasatiya, 

We've released new version, [2.2.1](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/2.2.1). If you'll still experience the same issue let us know and we'll try to do the fix with different approach.

**Comment by jkhasatiya** [comment] 2019-10-16 09:28
Hello @tjuric ,
Sure, Thank for the update.

**Comment by imspatni** [comment] 2019-10-16 11:52
@tjuric Thank you for update. Further we are providing `infobip_application_code` from string resources(as mentioned in standard guide [here](https://github.com/infobip/mobile-messaging-sdk-android)) not using builder class, please check if this information can help to debug issue better.

**Comment by imspatni** [comment] 2019-10-16 12:04
Please also refer following log, this is different from original post.

```
java.lang.RuntimeException: java.lang.NullPointerException
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:461)
	at org.infobip.mobile.messaging.mobile.MobileApiResourceProvider.getGenerator(MobileApiResourceProvider.java:165)
	at org.infobip.mobile.messaging.mobile.MobileApiResourceProvider.getMobileApiAppInstance(MobileApiResourceProvider.java:120)
	at org.infobip.mobile.messaging.MobileMessagingCore.installationSynchronizer(MobileMessagingCore.java:1657)
	at org.infobip.mobile.messaging.MobileMessagingCore.syncInstallation(MobileMessagingCore.java:348)
	at org.infobip.mobile.messaging.MobileMessagingCore.performSyncActions(MobileMessagingCore.java:331)
	at org.infobip.mobile.messaging.MobileMessagingCore.retrySyncOnNetworkAvailable(MobileMessagingCore.java:326)
	at org.infobip.mobile.messaging.platform.MobileMessagingJobService.onStartJob(MobileMessagingJobService.java:48)
	at android.app.job.JobService$1.onStartJob(JobService.java:62)
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
	... 6 more
```

**Comment by tjuric** [comment] 2019-10-16 12:15
@imspatni thanks for the additional stacktrace. 

It seems to be a different one internally in Android, but looking at the code of `JobServiceEngine.handleMessage()` and `JobService.handleMessage()` the cause is the same - job was interrupted with NullPointerException and it leads to NPE in `getGenerator` method.

**Comment by tjuric** [comment] 2020-05-06 08:35
Hi @imspatni,
Do you still experience this bug and for which SDK version?

BR,
Tereza

**Comment by tjuric** [comment] 2020-07-14 11:02
Closed due to inactivity.

**Closed as completed** 2020-07-14 11:02 UTC
