### ISSUE TITLE
GCM always used as PushServiceType

### ISSUE THREAD

**Issue by pedrohrsilva** [infobip/mobile-messaging-sdk-android#17] opened 2019-11-18 19:12 UTC
Checking method **Installation.PushServiceType** on **Platform.java**
We can check that GCM is used as PushServiceType if GCM dependency is included in the project. 

This used to work because in version 2.1 GCM dependency was included using scope _"provided"_
You can check this looking in **infobip-mobile-messaging-android-sdk/build.gradle** on version 2.1
(https://github.com/infobip/mobile-messaging-sdk-android/blob/2.1.0/infobip-mobile-messaging-android-sdk/build.gradle)

 In version 2.2 all the dependencies were included using scope _"api"_  (https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-sdk/build.gradle)

**Because of this GCM is always included in project, therefore GCM is always selected as PushServiceType**

**Comment by tjuric** [comment] 2019-11-18 19:56
Hey @pedrohrsilva,

We've noticed this bug today on versions 2.2.0 and 2.2.1 (since Gradle was updated). We'll provide a fix soon.

**Comment by tjuric** [comment] 2019-11-18 20:45
I've just released new version [2.2.2](https://github.com/infobip/mobile-messaging-sdk-android/issues/17) with bugfix for mentioned issue.

Issue was in mistakenly using both GCM and Firebase although GCM is and should've been optional. As already mentioned, affected versions were 2.2.0 and 2.2.1.

Please, test it and update us if you notice any other problems.

**Comment by pedrohrsilva** [comment] 2019-11-18 21:24
To test the fix I need that the version 2.2.2 published at Maven/Jcenter.
How long does it take to be updated there?

**Comment by tjuric** [comment] 2019-11-18 21:49
Usually around an hour. It's already on Bintray since the moment I wrote to you, you can check it up here https://bintray.com/infobip/maven/infobip-mobile-messaging-android-sdk/2.2.2.

**Comment by tjuric** [comment] 2019-11-20 14:17
Hi @pedrohrsilva, 

Can you tell us if this release fixed your issue so that we can close this thread?

**Comment by pedrohrsilva** [comment] 2019-11-26 14:27
Hey @tjuric,
we are testing the fix,
but are experiencing crashes when a user receives a push notification.

We are still investigating further.

**Comment by tjuric** [comment] 2019-11-26 14:30
Hi @pedrohrsilva,
We're in progress of implementing a fix, found the root cause and will give a notice in release notes once we distribute it.

**Comment by pedroatanasio** [comment] 2019-12-05 18:17
Any updates on this issue?

**Comment by pedrohrsilva** [comment] 2019-12-05 18:19
Infobip SDK still crash the app.

**Comment by tjuric** [comment] 2019-12-13 12:27
Sorry for the late response. 
We've had some unexpected issues in preparation of this release, but by Wednesday Dec 18th we'll release version 2.3.0 that will work with Firebase by default. 

I'll update you about it on this thread.

**Comment by tjuric** [comment] 2020-02-27 17:54
Hi @pedroatanasio & @pedrohrsilva, 
We've released version [2.3.0](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/2.3.0) on 18th of December, as agreed, that works with Firebase only. No changes in code are needed. We have also released one more version [2.3.1](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/2.3.1) with additional minor bug fixes.

I forgot to update you here on the thread, but you could've checked our releases. 

I'm closing this thread. You might reopen it if you experience any other issues related to the same issue.

BR,
Tereza

**Closed as completed by tjuric** 2020-02-27 17:54 UTC
